### ISSUE TITLE
pack_nが重い

### ISSUE THREAD

**Issue by YSRKEN** [YSRKEN/Shioi#9]
次の棋譜でベンチしつつ、プロファイラで原因を探りました。
棋譜：h8,h7,h6,i7,j7,g7,f7,g6,g8,i8,j9,i9,i6,j8,h9,e6,g9,iA,iB,jA,hA,f8,gA,jB,hB,hC,iC,f9,gB,gC,fB,eB,fA,k9,jC,kD,iD,kA,lA,kB,kC,jD,**,

結果、PackedStone::pack_nが重いことが判明しました。論理上正常に稼働すれば問題なく次のネタ(追い詰め実装)を仕込めますが、yumetodoさん、速度を改善させる方法で何か思いつくことはありますか？
![2016-04-22_011412](https://cloud.githubusercontent.com/assets/3734392/14716337/8d9c0de8-0827-11e6-816b-c505da271e96.png)

**Comment by yumetodo** [comment]
そもそもコンパイル時に評価できないのが解せないな・・・。一応再帰自体を早くすることはできると思うけど

**Comment by yumetodo** [comment]
結論：VSのバグ

例えば

``` cpp
constexpr std::array<PackedStone, 2> sss = { { Stone::None | Stone::Black, Stone::Black**2_pack | Stone::None | Stone::Black } };
```

こんな式が

```
fatal error C1001: コンパイラで内部エラーが発生しました。
```

と怒られる。もちろんClang with Microsoft CodeGenはちゃんと動く

**Comment by yumetodo** [comment]
ただ

``` cpp
constexpr PackedStone nb = Stone::None | Stone::Black;
```

これは問題なく通してくれるのでまあそうする方向で考えます

**Comment by yumetodo** [comment]
これでどうかな

**Comment by YSRKEN** [comment]
出先のPC(たまたまi7-4790Kで、上記テストPCと同じCPU)でテストしたところ、PGO無しでも1198[ms]、PGO有りだと895[ms]になりました。Ver.0.7.0だと1215[ms]でしたので、実に26％減！ワッショイ！

**Comment by yumetodo** [comment]
やったぜ

**Comment by YSRKEN** [comment]
じゃけんCloseしますね
